### ISSUE TITLE
500 Error: transaction cannot be null

### ISSUE THREAD

**Issue by kucits** [blueriver/MuraGoogleSitemaps#14]
Installed the latest version (4.2.0) from the github repository and when I try to access the admin I get:

500 Error
transaction cannot be null
Code:0
Type:java.lang.IllegalArgumentException
lucee.runtime.exp.NativeException: transaction cannot be null
	at lucee.runtime.exp.NativeException.newInstance(NativeException.java:73)
	at lucee.runtime.op.Caster.toPageException(Caster.java:3201)
	at lucee.runtime.op.Caster.toPageException(Caster.java:3176)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:349)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:225)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1701)
	at includes.framework.one_cfc$cf.udfCall5(/MuraGoogleSitemaps/includes/framework/one.cfc:781)
	at includes.framework.one_cfc$cf.udfCall(/MuraGoogleSitemaps/includes/framework/one.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:338)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:225)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:420)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:222)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2408)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2398)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2366)
	at lucee.runtime.engine.Request.run(Request.java:34)

Column: 0
ID: ??
Line: 781
Raw Trace: includes.framework.one_cfc$cf.udfCall5(/MuraGoogleSitemaps/includes/framework/one.cfc:781)
Template: C:\path\plugins\MuraGoogleSitemaps\includes\framework\one.cfc
Type: cfml

**Comment by grantshepert** [comment]
What version of Mura are you using?

**Comment by kucits** [comment]
7.0.7057

**Comment by grantshepert** [comment]
Can you post the entire error message up? It looks like there's a controller missing, but I can't see which one it would be.

**Comment by kucits** [comment]
MuraGoogleSitemaps ERROR
Catch
additional
Struct (ordered)
Cause
Struct
additional
Struct (ordered)
Detail
string
ErrorCode
string 0
Extended_Info
string
ExtendedInfo
string
Message
string transaction cannot be null
StackTrace
string lucee.runtime.exp.NativeException: transaction cannot be null at
lucee.runtime.exp.NativeException.newInstance(NativeException.java:73) at
lucee.runtime.op.Caster.toPageException(Caster.java:3201) at
lucee.runtime.op.Caster.toPageException(Caster.java:3176) at
lucee.runtime.type.UDFImpl._call(UDFImpl.java:349) at
lucee.runtime.type.UDFImpl.call(UDFImpl.java:225) at
lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772) at
lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1701) at
plugins.muragooglesitemaps.includes.framework.one_cfc$cf.udfCall5(/plugins/MuraGoogleSitemaps/includes/framework/one.cfc:781)
at
plugins.muragooglesitemaps.includes.framework.one_cfc$cf.udfCall(/plugins/MuraGoogleSitemaps/includes/framework/one.cfc)
at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at
lucee.runtime.type.UDFImpl._call(UDFImpl.java:338) at
lucee.runtime.type.UDFImpl.call(UDFImpl.java:225) at
lucee.runtime.ComponentImpl._call(ComponentImpl.java:697) at
lucee.runtime.ComponentImpl._call(ComponentImpl.java:580) at
lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918) at
lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:420)
at
lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:222)
at
lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)
at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2408) at
lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2398) at
lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2366) at
lucee.runtime.engine.Request.run(Request.java:34)
TagContext
Array
1
Struct
codePrintHTML
string 779: if ( !structKeyExists( once, tuple.key ) ) {
780: once[ tuple.key ] = i;
*781: doController( tuple, 'before', 'before' );*
782: if ( structKeyExists( request._fw1, 'abortController' ) )
abortController();
783: }
codePrintPlain
string 779: if ( !structKeyExists( once, tuple.key ) ) { 780: once[
tuple.key ] = i; 781: doController( tuple, 'before', 'before' ); 782: if (
structKeyExists( request._fw1, 'abortController' ) ) abortController();
783: }
column
number 0
id
string ??
line
number 781
Raw_Trace
string
plugins.muragooglesitemaps.includes.framework.one_cfc$cf.udfCall5(/plugins/MuraGoogleSitemaps/includes/framework/one.cfc:781)
template
string
E:\wwwroot\www-kings\plugins\MuraGoogleSitemaps\includes\framework\one.cfc
type
string cfml
type
string java.lang.IllegalArgumentException
Detail
string
ErrorCode
string 0
Extended_Info
string
ExtendedInfo
string
Message
string transaction cannot be null
name
string onRequest
rootCause
Struct
additional
Struct (ordered)
Detail
string
ErrorCode
string 0
Extended_Info
string
ExtendedInfo
string
Message
string transaction cannot be null
StackTrace
string lucee.runtime.exp.NativeException: transaction cannot be null at
lucee.runtime.exp.NativeException.newInstance(NativeException.java:73) at
lucee.runtime.op.Caster.toPageException(Caster.java:3201) at
lucee.runtime.op.Caster.toPageException(Caster.java:3176) at
lucee.runtime.type.UDFImpl._call(UDFImpl.java:349) at
lucee.runtime.type.UDFImpl.call(UDFImpl.java:225) at
lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772) at
lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1701) at
plugins.muragooglesitemaps.includes.framework.one_cfc$cf.udfCall5(/plugins/MuraGoogleSitemaps/includes/framework/one.cfc:781)
at
plugins.muragooglesitemaps.includes.framework.one_cfc$cf.udfCall(/plugins/MuraGoogleSitemaps/includes/framework/one.cfc)
at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at
lucee.runtime.type.UDFImpl._call(UDFImpl.java:338) at
lucee.runtime.type.UDFImpl.call(UDFImpl.java:225) at
lucee.runtime.ComponentImpl._call(ComponentImpl.java:697) at
lucee.runtime.ComponentImpl._call(ComponentImpl.java:580) at
lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918) at
lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:420)
at
lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:222)
at
lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)
at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2408) at
lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2398) at
lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2366) at
lucee.runtime.engine.Request.run(Request.java:34)
TagContext
Array
1
Struct
codePrintHTML
string 779: if ( !structKeyExists( once, tuple.key ) ) {
780: once[ tuple.key ] = i;
*781: doController( tuple, 'before', 'before' );*
782: if ( structKeyExists( request._fw1, 'abortController' ) )
abortController();
783: }
codePrintPlain
string 779: if ( !structKeyExists( once, tuple.key ) ) { 780: once[
tuple.key ] = i; 781: doController( tuple, 'before', 'before' ); 782: if (
structKeyExists( request._fw1, 'abortController' ) ) abortController();
783: }
column
number 0
id
string ??
line
number 781
Raw_Trace
string
plugins.muragooglesitemaps.includes.framework.one_cfc$cf.udfCall5(/plugins/MuraGoogleSitemaps/includes/framework/one.cfc:781)
template
string
E:\wwwroot\www-kings\plugins\MuraGoogleSitemaps\includes\framework\one.cfc
type
string cfml
type
string java.lang.IllegalArgumentException
StackTrace
string lucee.runtime.exp.NativeException: transaction cannot be null at
lucee.runtime.exp.NativeException.newInstance(NativeException.java:73) at
lucee.runtime.op.Caster.toPageException(Caster.java:3201) at
lucee.runtime.op.Caster.toPageException(Caster.java:3176) at
lucee.runtime.type.UDFImpl._call(UDFImpl.java:349) at
lucee.runtime.type.UDFImpl.call(UDFImpl.java:225) at
lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772) at
lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1701) at
plugins.muragooglesitemaps.includes.framework.one_cfc$cf.udfCall5(/plugins/MuraGoogleSitemaps/includes/framework/one.cfc:781)
at
plugins.muragooglesitemaps.includes.framework.one_cfc$cf.udfCall(/plugins/MuraGoogleSitemaps/includes/framework/one.cfc)
at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106) at
lucee.runtime.type.UDFImpl._call(UDFImpl.java:338) at
lucee.runtime.type.UDFImpl.call(UDFImpl.java:225) at
lucee.runtime.ComponentImpl._call(ComponentImpl.java:697) at
lucee.runtime.ComponentImpl._call(ComponentImpl.java:580) at
lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918) at
lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:420)
at
lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:222)
at
lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)
at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2408) at
lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2398) at
lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2366) at
lucee.runtime.engine.Request.run(Request.java:34)
TagContext
Array
1
Struct
codePrintHTML
string 779: if ( !structKeyExists( once, tuple.key ) ) {
780: once[ tuple.key ] = i;
*781: doController( tuple, 'before', 'before' );*
782: if ( structKeyExists( request._fw1, 'abortController' ) )
abortController();
783: }
codePrintPlain
string 779: if ( !structKeyExists( once, tuple.key ) ) { 780: once[
tuple.key ] = i; 781: doController( tuple, 'before', 'before' ); 782: if (
structKeyExists( request._fw1, 'abortController' ) ) abortController();
783: }
column
number 0
id
string ??
line
number 781
Raw_Trace
string
plugins.muragooglesitemaps.includes.framework.one_cfc$cf.udfCall5(/plugins/MuraGoogleSitemaps/includes/framework/one.cfc:781)
template
string
E:\wwwroot\www-kings\plugins\MuraGoogleSitemaps\includes\framework\one.cfc
type
string cfml
type
string java.lang.IllegalArgumentException

**Comment by kucits** [comment]
Updated Mura to 7.0.7074 and the plugin is working as expected. Must have been an issue with the previous Mura version (I think it was 7.0.5xxx).
